# This is a basic workflow to help you get started with Actions
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
          submodules: true
          ref: master

      - name: Install and Build üîß # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          export DEPLOY_BRANCH="gh-pages-master"
          npm install
          CDN_URL="https://cdn.jsdelivr.net/gh/pkuhollow/webhole@$DEPLOY_BRANCH"
          VERSION_NUMBER="v$(grep -oP '"version": "\K[^"]+' package.json | head -n1)"
          echo "DEPLOY_BRANCH=$DEPLOY_BRANCH, VERSION_NUMBER=$VERSION_NUMBER, CDN_URL=$CDN_URL"
          CI=false PUBLIC_URL=$CDN_URL REACT_APP_BUILD_INFO=$VERSION_NUMBER npm run build
          sed -i 's|https://cdn.jsdelivr.net/gh/pkuhollow/webhole@'"$DEPLOY_BRANCH"'/index.html|./index.html|g' build/*-*
          sed -i 's|https://cdn.jsdelivr.net/gh/pkuhollow/webhole@'"$DEPLOY_BRANCH"'/service-worker.js|./service-worker.js|g' build/*-*
          sed -i 's|"https://cdn.jsdelivr.net/gh/pkuhollow/webhole@'"$DEPLOY_BRANCH"'","/service-worker.js"|".","/service-worker.js"|' build/static/js/*.js
          sed -i 's|storage.googleapis.com/workbox-cdn/releases/4.3.1|cdn.jsdelivr.net/npm/workbox-cdn@4.3.1/workbox|g' build/service-worker.js
          
      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages-master # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
